services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: ${postgres_db}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -h db
      retries: 5
      start_period: 10s
      interval: 5s
      timeout: 5s
  web:
    image: bugsink/bugsink:2.5.1
    depends_on:
      - db
    restart: unless-stopped
    expose:
      - 8000
    environment:
      SECRET_KEY: ${secret_key}
      CREATE_SUPERUSER: ${superuser}
      PORT: 8000
      DATABASE_URL: postgresql://${postgres_user}:${postgres_password}@db:5432/${postgres_db}
      BEHIND_HTTPS_PROXY: ${behind_https_proxy}
      BASE_URL: https://${main_domain}
    healthcheck:
      test:
        - CMD-SHELL
        - python -c 'import requests;
          requests.get("http://localhost:8000/").raise_for_status()'
      interval: 5s
      timeout: 20s
      retries: 10
    volumes: []
volumes:
  db-data: null
