[variables]
main_domain = "${domain}"
wa_user = "admin"
wa_password = "${password:32}"

[[routes]]
service = "whatsapp"
port = 3080
host = "${main_domain}"

[env]
WA_USER = "${wa_user}"
WA_PASSWORD = "${wa_password}"
