services:
  nginx:
    image: nginx:1.31.5-trixie-perl
    restart: unless-stopped
    expose:
      - 80
      - 443
    volumes:
      - nginx-config:/etc/nginx
      - nginx-html:/usr/share/nginx/html
volumes:
  nginx-config: {}
  nginx-html: {}
