[variables]
main_domain = "${domain}"
db_user = "bigcapital"
db_password = "${password:32}"
db_root_password = "${password:32}"
db_charset = "utf8mb4"
system_db_name = "bigcapital"
tenant_db_name_prefix = "bigcapital_tenant_"
jwt_secret = "${hash:64}"
mail_port = "587"
mail_secure = "false"
mail_from_name = "BigCapital"
agendash_auth_user = "admin"
agendash_auth_password = "${password:24}"
signup_disabled = "false"
signup_email_confirmation = "false"
gotenberg_url = "http://gotenberg:9000"
gotenberg_docs_url = "http://gotenberg:9000"
exchange_rate_service = "openexchangerates"
banking_connect = "false"
plaid_env = "sandbox"
hosted_on_bigcapital_cloud = "false"
new_relic_distributed_tracing_enabled = "false"
new_relic_log = "false"
new_relic_ai_monitoring_enabled = "false"
new_relic_custom_insights_events_max_samples_stored = "10000"
new_relic_span_events_max_samples_stored = "10000"
new_relic_app_name = "BigCapital"
mail_username = "CHANGEME-mail_username"
mail_password = "${password:32}"
signup_allowed_emails = "CHANGEME-signup_allowed_emails"
open_exchange_rate_app_id = "CHANGEME-open_exchange_rate_app_id"
plaid_client_id = "CHANGEME-plaid_client_id"
plaid_secret = "${password:32}"
plaid_link_webhook = "CHANGEME-plaid_link_webhook"
lemonsqueezy_api_key = "${password:32}"
lemonsqueezy_store_id = "CHANGEME-lemonsqueezy_store_id"
lemonsqueezy_webhook_secret = "${password:32}"
new_relic_license_key = "CHANGEME-new_relic_license_key"
s3_region = "CHANGEME-s3_region"
s3_access_key_id = "${password:32}"
s3_secret_access_key = "${password:32}"
s3_endpoint = "CHANGEME-s3_endpoint"
s3_bucket = "CHANGEME-s3_bucket"

[[routes]]
service = "webapp"
port = 80
host = "${main_domain}"

[env]
base_url = "https://${main_domain}"
mail_from_address = "noreply@${main_domain}"
MAIL_HOST = "${main_domain}"
MAIL_USERNAME = "${mail_username}"
MAIL_PASSWORD = "${mail_password}"
MAIL_PORT = "${mail_port}"
MAIL_SECURE = "${mail_secure}"
MAIL_FROM_NAME = "${mail_from_name}"
MAIL_FROM_ADDRESS = "noreply@${main_domain}"
DB_HOST = "mysql"
DB_USER = "${db_user}"
DB_PASSWORD = "${db_password}"
DB_CHARSET = "${db_charset}"
SYSTEM_DB_NAME = "${system_db_name}"
TENANT_DB_NAME_PERFIX = "${tenant_db_name_prefix}"
JWT_SECRET = "${jwt_secret}"
MONGODB_DATABASE_URL = "mongodb://mongo/bigcapital"
BASE_URL = "https://${main_domain}"
AGENDASH_AUTH_USER = "${agendash_auth_user}"
AGENDASH_AUTH_PASSWORD = "${agendash_auth_password}"
SIGNUP_DISABLED = "${signup_disabled}"
SIGNUP_ALLOWED_DOMAINS = "${main_domain}"
SIGNUP_ALLOWED_EMAILS = "${signup_allowed_emails}"
SIGNUP_EMAIL_CONFIRMATION = "${signup_email_confirmation}"
GOTENBERG_URL = "${gotenberg_url}"
GOTENBERG_DOCS_URL = "${gotenberg_docs_url}"
EXCHANGE_RATE_SERVICE = "${exchange_rate_service}"
OPEN_EXCHANGE_RATE_APP_ID = "${open_exchange_rate_app_id}"
BANKING_CONNECT = "${banking_connect}"
PLAID_ENV = "${plaid_env}"
PLAID_CLIENT_ID = "${plaid_client_id}"
PLAID_SECRET = "${plaid_secret}"
PLAID_LINK_WEBHOOK = "${plaid_link_webhook}"
LEMONSQUEEZY_API_KEY = "${lemonsqueezy_api_key}"
LEMONSQUEEZY_STORE_ID = "${lemonsqueezy_store_id}"
LEMONSQUEEZY_WEBHOOK_SECRET = "${lemonsqueezy_webhook_secret}"
HOSTED_ON_BIGCAPITAL_CLOUD = "${hosted_on_bigcapital_cloud}"
NEW_RELIC_DISTRIBUTED_TRACING_ENABLED = "${new_relic_distributed_tracing_enabled}"
NEW_RELIC_LOG = "${new_relic_log}"
NEW_RELIC_AI_MONITORING_ENABLED = "${new_relic_ai_monitoring_enabled}"
NEW_RELIC_CUSTOM_INSIGHTS_EVENTS_MAX_SAMPLES_STORED = "${new_relic_custom_insights_events_max_samples_stored}"
NEW_RELIC_SPAN_EVENTS_MAX_SAMPLES_STORED = "${new_relic_span_events_max_samples_stored}"
NEW_RELIC_LICENSE_KEY = "${new_relic_license_key}"
NEW_RELIC_APP_NAME = "${new_relic_app_name}"
S3_REGION = "${s3_region}"
S3_ACCESS_KEY_ID = "${s3_access_key_id}"
S3_SECRET_ACCESS_KEY = "${s3_secret_access_key}"
S3_ENDPOINT = "${s3_endpoint}"
S3_BUCKET = "${s3_bucket}"
MYSQL_DATABASE = "${system_db_name}"
MYSQL_USER = "${db_user}"
MYSQL_PASSWORD = "${db_password}"
MYSQL_ROOT_PASSWORD = "${db_root_password}"
