services:
  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.10.8
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      - CMD_DB_URL=postgres://hedgedoc:${database_password}@database:5432/hedgedoc
      - CMD_DOMAIN=${main_domain}
      - CMD_PROTOCOL_USESSL=true
      - CMD_URL_ADDPORT=false
    volumes:
      - hedgedoc_uploads:/hedgedoc/public/uploads
    expose:
      - "3000"
  database:
    image: postgres:17.7-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=${database_password}
      - POSTGRES_DB=hedgedoc
    volumes:
      - hedgedoc_database:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U hedgedoc -d hedgedoc
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  hedgedoc_uploads: null
  hedgedoc_database: null
