services:
  checkcle:
    image: operacle/checkcle:v1.6.0
    restart: unless-stopped
    expose:
      - 8090
    volumes:
      - checkcle-data:/mnt/pb_data
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
volumes:
  checkcle-data: {}
