services:
  argilla-web:
    image: argilla/argilla-server:v2.8.0
    restart: unless-stopped
    expose:
      - 6900
    environment:
      - ARGILLA_HOME_PATH=/var/lib/argilla
      - ARGILLA_ELASTICSEARCH=http://argilla-elasticsearch:9200
      - ARGILLA_DATABASE_URL=postgresql+asyncpg://postgres:${db_password}@argilla-db:5432/argilla
      - ARGILLA_REDIS_URL=redis://:${redis_password}@argilla-redis:6379/0
      - USERNAME=${login_username}
      - PASSWORD=${login_password}
      - API_KEY=argilla.apikey
      - WORKSPACE=default
    volumes:
      - argilladata:/var/lib/argilla
    depends_on:
      - argilla-elasticsearch
      - argilla-db
      - argilla-redis
  argilla-worker:
    image: argilla/argilla-server:v2.8.0
    restart: unless-stopped
    environment:
      - BACKGROUND_NUM_WORKERS=2
      - ARGILLA_HOME_PATH=/var/lib/argilla
      - ARGILLA_ELASTICSEARCH=http://argilla-elasticsearch:9200
      - ARGILLA_DATABASE_URL=postgresql+asyncpg://postgres:${db_password}@argilla-db:5432/argilla
      - ARGILLA_REDIS_URL=redis://:${redis_password}@argilla-redis:6379/0
    volumes:
      - argilladata:/var/lib/argilla
    command: python -m argilla_server worker --num-workers 2
    depends_on:
      - argilla-elasticsearch
      - argilla-db
      - argilla-redis
  argilla-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    restart: unless-stopped
    environment:
      - node.name=elasticsearch
      - cluster.name=es-argilla-local
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
  argilla-db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_DB=argilla
    volumes:
      - dbdata:/var/lib/postgresql/data
  argilla-redis:
    image: redis:7-alpine
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${redis_password}
    command: redis-server --requirepass ${redis_password}
    volumes:
      - redisdata:/data
volumes:
  argilladata: {}
  elasticdata: {}
  dbdata: {}
  redisdata: {}
