[variables]
mautic_domain = "${domain}"
pma_domain = "${domain}"
MYSQL_ROOT_PASSWORD = "${password:32}"
MAUTIC_DB_PASSWORD = "${password:32}"

[[routes]]
service = "mautic"
port = 80
host = "${mautic_domain}"
label = "Mautic"

[[routes]]
service = "phpmyadmin"
port = 80
host = "${pma_domain}"
label = "Database manager"
