[variables]
gateway_token = "${password:32}"
CLAUDE_AI_SESSION_KEY = "CHANGEME-CLAUDE_AI_SESSION_KEY"
CLAUDE_WEB_SESSION_KEY = "CHANGEME-CLAUDE_WEB_SESSION_KEY"
CLAUDE_WEB_COOKIE = "CHANGEME-CLAUDE_WEB_COOKIE"
moltbot_gateway_domain = "${domain}"

[[routes]]
service = "moltbot-gateway"
port = 18789
host = "${moltbot_gateway_domain}"

[env]
CLAWDBOT_GATEWAY_TOKEN = "${gateway_token}"
CLAWDBOT_GATEWAY_PORT = "18789"
CLAWDBOT_BRIDGE_PORT = "18790"
CLAWDBOT_GATEWAY_BIND = "lan"
CLAWDBOT_PLUGINS = "discord,memory-core"
OPENROUTER_API_KEY = "YOUR-API-KEY"
