services:
  backend:
    image: ghcr.io/leonmuscoden/letterfeed-backend:0.5.3
    restart: unless-stopped
    environment:
      LETTERFEED_APP_BASE_URL: https://${main_domain}
      LETTERFEED_BACKEND_URL: http://backend:8000
      LETTERFEED_DATABASE_URL: sqlite:////data/letterfeed.db
      LETTERFEED_IMAP_SERVER: ""
      LETTERFEED_IMAP_USERNAME: ""
      LETTERFEED_IMAP_PASSWORD: ""
      LETTERFEED_SEARCH_FOLDER: INBOX
      LETTERFEED_MOVE_TO_FOLDER: ""
      LETTERFEED_MARK_AS_READ: "true"
      LETTERFEED_EMAIL_CHECK_INTERVAL: "15"
      LETTERFEED_AUTO_ADD_NEW_SENDERS: "false"
      LETTERFEED_SECRET_KEY: ${secret_key}
      LETTERFEED_AUTH_USERNAME: admin
      LETTERFEED_AUTH_PASSWORD: ${auth_password}
    volumes:
      - letterfeed_data:/data
  frontend:
    image: ghcr.io/leonmuscoden/letterfeed-frontend:0.5.3
    restart: unless-stopped
    environment:
      LETTERFEED_APP_BASE_URL: https://${main_domain}
      LETTERFEED_BACKEND_URL: http://backend:8000
    expose:
      - 3000
    depends_on:
      - backend
    volumes: []
volumes:
  letterfeed_data: null
