[variables]
main_domain = "${domain}"
TZ = "UTC"
POSTGRES_USER = "CHANGEME-POSTGRES_USER"
POSTGRES_PASSWORD = "${password:32}"
POSTGRES_DB = "CHANGEME-POSTGRES_DB"
MM_SQLSETTINGS_DRIVERNAME = "CHANGEME-MM_SQLSETTINGS_DRIVERNAME"
MM_SQLSETTINGS_DATASOURCE = "CHANGEME-MM_SQLSETTINGS_DATASOURCE"
MM_BLEVESETTINGS_INDEXDIR = "CHANGEME-MM_BLEVESETTINGS_INDEXDIR"
APP_PORT = "CHANGEME-APP_PORT"

[[routes]]
service = "mattermost"
port = 8065
host = "${main_domain}"

[env]
Domain = "${main_domain}"
POSTGRES_USER = "mmuser"
POSTGRES_PASSWORD = "32"
POSTGRES_DB = "mattermost"
MM_SQLSETTINGS_DRIVERNAME = "postgres"
MM_SQLSETTINGS_DATASOURCE = "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable&connect_timeout=10"
APP_PORT = "8065"
TZ = "UTC"
