[variables]
main_domain = "${domain}"

[[routes]]
service = "web-check"
port = 3000
host = "${main_domain}"

[env]
TRANCO_USERNAME = ""
PORT = "3000"
DISABLE_GUI = "false"
API_TIMEOUT_LIMIT = "10000"
API_CORS_ORIGIN = "*"
API_ENABLE_RATE_LIMIT = "true"
ENABLE_ANALYTICS = "false"
