services:
  crawlab-worker:
    image: crawlabteam/crawlab:0.6.3
    restart: unless-stopped
    environment:
      - CRAWLAB_NODE_MASTER=N
      - CRAWLAB_GRPC_ADDRESS=${MASTER_GRPC_ADDRESS}
      - CRAWLAB_FS_FILER_URL=${MASTER_FILER_URL}
    volumes:
      - crawlab-worker-data:/root/.crawlab
      - crawlab-worker-app:/data
volumes:
  crawlab-worker-data: null
  crawlab-worker-app: null
