services:
  lubelogger:
    image: ghcr.io/hargata/lubelogger:v1.6.5
    restart: unless-stopped
    environment:
      - LC_ALL=${lubelogger_locale}
      - LANG=${lubelogger_locale}
      - LUBELOGGER_DOMAIN=https://${main_domain}
      - EnableAuth=${lubelogger_enable_auth}
    volumes:
      - lubelogger-data:/App/data
      - lubelogger-keys:/root/.aspnet/DataProtection-Keys
    expose:
      - 8080
volumes:
  lubelogger-data: {}
  lubelogger-keys: {}
