[variables]
main_domain = "${domain}"
postgres_db = "litellm"
postgres_user = "litellm"
postgres_password = "${password:32}"
ui_username = "${username}"
ui_password = "${password:32}"
litellm_master_key = "${password:64}"
or_app_name = "LiteLLM Example app"
openai_api_key = "${password:32}"
cohere_api_key = "${password:32}"
or_api_key = "${password:32}"
azure_api_base = "CHANGEME-azure_api_base"
azure_api_version = "CHANGEME-azure_api_version"
azure_api_key = "${password:32}"
replicate_api_key = "${password:32}"
replicate_api_token = "${password:32}"
anthropic_api_key = "${password:32}"
infisical_token = "${password:32}"
novita_api_key = "${password:32}"
infinity_api_key = "${password:32}"

[[routes]]
service = "litellm"
port = 4000
host = "${main_domain}"

[env]
DATABASE_URL = "postgresql://${postgres_user}:${postgres_password}@litellm-db:5432/${postgres_db}"
POSTGRES_DB = "${postgres_db}"
POSTGRES_USER = "${postgres_user}"
POSTGRES_PASSWORD = "${postgres_password}"
UI_USERNAME = "${ui_username}"
UI_PASSWORD = "${ui_password}"
LITELLM_MASTER_KEY = "${litellm_master_key}"
STORE_MODEL_IN_DB = "True"
OPENAI_API_KEY = "${openai_api_key}"
OPENAI_BASE_URL = "${main_domain}"
COHERE_API_KEY = "${cohere_api_key}"
OR_SITE_URL = "${main_domain}"
OR_APP_NAME = "${or_app_name}"
OR_API_KEY = "${or_api_key}"
AZURE_API_BASE = "${azure_api_base}"
AZURE_API_VERSION = "${azure_api_version}"
AZURE_API_KEY = "${azure_api_key}"
REPLICATE_API_KEY = "${replicate_api_key}"
REPLICATE_API_TOKEN = "${replicate_api_token}"
ANTHROPIC_API_KEY = "${anthropic_api_key}"
INFISICAL_TOKEN = "${infisical_token}"
NOVITA_API_KEY = "${novita_api_key}"
INFINITY_API_KEY = "${infinity_api_key}"
