services:
  kokoro-web:
    image: ghcr.io/eduardolat/kokoro-web:0.1.3-arm64
    restart: unless-stopped
    environment:
      - KW_SECRET_API_KEY=${api_key}
      - KW_PUBLIC_NO_TRACK=${no_track}
    volumes:
      - kokoro-cache:/kokoro/cache
    expose:
      - 3000
volumes:
  kokoro-cache: {}
