[variables]
main_domain = "${domain}"
password = "${password:16}"
AUTO_PASSWORD_1 = "${password}"
AUTO_PASSWORD_2 = "${password}"

[[routes]]
service = "calibre"
port = 8080
host = "${main_domain}"

[env]
PASSWORD = "${AUTO_PASSWORD_2}"
