[variables]
main_domain = "${domain}"
console_domain = "${domain}"
password = "${password:32}"
AUTO_PASSWORD_1 = "${password}"
AUTO_PASSWORD_2 = "${password}"

[[routes]]
service = "silo"
port = 9000
host = "${main_domain}"

[[routes]]
service = "silo"
port = 9001
host = "${console_domain}"

[env]
MINIO_ROOT_USER = "silo_usr"
MINIO_ROOT_PASSWORD = "${AUTO_PASSWORD_2}"
