services:
  influxdb:
    image: influxdb:2.7.10
    restart: unless-stopped
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    expose:
      - 8086
volumes:
  influxdb2-data: null
  influxdb2-config: null
