services:
  komari:
    image: ghcr.io/komari-monitor/komari:1.5.0-fix1
    restart: unless-stopped
    volumes:
      - komari-data:/app/data
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    expose:
      - 25774
volumes:
  komari-data: {}
