services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${postgres_password}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      retries: 5
  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z.hotfix.7aa24e772
    command: server /data
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${minio_user}
      MINIO_ROOT_PASSWORD: ${minio_password}
    expose:
      - 9000
  chrome:
    image: ghcr.io/browserless/chromium:v2.18.0
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      TIMEOUT: 10000
      CONCURRENT: 10
      TOKEN: ${chrome_token}
      EXIT_ON_HEALTH_FAILURE: "true"
      PRE_REQUEST_HEALTH_CHECK: "true"
    volumes: []
  app:
    image: amruthpillai/reactive-resume:v5.3.0
    depends_on:
      - postgres
      - minio
      - chrome
    environment:
      PORT: 3000
      NODE_ENV: production
      PUBLIC_URL: https://${main_domain_app}
      STORAGE_URL: https://${main_domain_app}/default
      CHROME_TOKEN: ${chrome_token}
      CHROME_URL: ws://chrome:3000
      DATABASE_URL: postgresql://postgres:${postgres_password}@postgres:5432/postgres
      ACCESS_TOKEN_SECRET: ${access_token_secret}
      REFRESH_TOKEN_SECRET: ${refresh_token_secret}
      MAIL_FROM: noreply@${main_domain_app}
      STORAGE_ENDPOINT: minio
      STORAGE_PORT: 9000
      STORAGE_REGION: us-east-1
      STORAGE_BUCKET: default
      STORAGE_ACCESS_KEY: ${minio_user}
      STORAGE_SECRET_KEY: ${minio_password}
      STORAGE_USE_SSL: "false"
      STORAGE_SKIP_BUCKET_CHECK: "false"
    volumes: []
    expose:
      - 3000
volumes:
  minio_data: null
  postgres_data: null
