services:
  go2rtc:
    image: alexxit/go2rtc:1.9.14
    restart: unless-stopped
    expose:
      - 1984
      - 8554
      - 8555
    environment:
      - TZ=${TZ}
    volumes:
      - go2rtc-config:/config
volumes:
  go2rtc-config: {}
