services:
  blinko-website:
    image: blinkospace/blinko:1.6.3
    environment:
      NODE_ENV: production
      NEXTAUTH_SECRET: ${nextauth_secret}
      DATABASE_URL: postgresql://postgres:${postgres_password}@blinko-postgres:5432/postgres
      NEXTAUTH_URL: http://${main_domain}
      NEXT_PUBLIC_BASE_URL: http://${main_domain}
    depends_on:
      - blinko-postgres
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    expose:
      - 1111
    volumes: []
  blinko-postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${postgres_password}
      TZ: Asia/Shanghai
    volumes:
      - blinko-db:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - postgres
        - -d
        - postgres
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  blinko-db: {}
