services:
  ryot-app:
    image: ignisda/ryot:v7.10
    environment:
      - DATABASE_URL=postgres://postgres:${postgres_password}@ryot-db:5432/postgres
      - SERVER_ADMIN_ACCESS_TOKEN=${admin_access_token}
      - TZ=UTC
    depends_on:
      ryot-db:
        condition: service_healthy
    restart: always
    pull_policy: always
    volumes: []
    expose:
      - 8000
  ryot-db:
    image: postgres:16-alpine
    volumes:
      - ryot-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - TZ=UTC
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  ryot-postgres-data: null
