services:
  agent-zero:
    image: agent0ai/agent-zero:v1.9
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - AUTH_LOGIN=${auth_login}
      - AUTH_PASSWORD=${auth_password}
    volumes:
      - agent-zero-data:/a0/usr
volumes:
  agent-zero-data: null
