services:
  flarum:
    image: crazymax/flarum:1.8.19
    restart: unless-stopped
    expose:
      - 8000
    environment:
      - FLARUM_BASE_URL=https://${main_domain}
      - DB_HOST=db
      - DB_NAME=${db_name}
      - DB_USER=${db_user}
      - DB_PASSWORD=${db_password}
    volumes:
      - flarum-data:/data
    depends_on:
      - db
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${db_root_password}
      - MYSQL_DATABASE=${db_name}
      - MYSQL_USER=${db_user}
      - MYSQL_PASSWORD=${db_password}
    volumes:
      - db-data:/var/lib/mysql
volumes:
  flarum-data: {}
  db-data: {}
