services:
  ackee:
    image: electerious/ackee:3.4.2
    expose:
      - "3000"
    environment:
      - ACKEE_USERNAME=${ACKEE_USERNAME}
      - ACKEE_PASSWORD=${ACKEE_PASSWORD}
      - ACKEE_MONGODB=mongodb://mongo:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017
    volumes: []
  mongo:
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=mongo
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: null
