[variables]
main_domain = "${domain}"
jitsi_image_version = "unstable"
jicofo_auth_password = "${password:32}"
jvb_auth_password = "${password:32}"
jicofo_component_secret = "${password:32}"
TZ = "UTC"
ENABLE_AUTH = "CHANGEME-ENABLE_AUTH"
ENABLE_GUESTS = "CHANGEME-ENABLE_GUESTS"
ENABLE_LETSENCRYPT = "CHANGEME-ENABLE_LETSENCRYPT"
ENABLE_HTTP_REDIRECT = "CHANGEME-ENABLE_HTTP_REDIRECT"
ENABLE_XMPP_WEBSOCKET = "CHANGEME-ENABLE_XMPP_WEBSOCKET"
ENABLE_COLIBRI_WEBSOCKET = "CHANGEME-ENABLE_COLIBRI_WEBSOCKET"
DISABLE_HTTPS = "CHANGEME-DISABLE_HTTPS"
JICOFO_AUTH_USER = "CHANGEME-JICOFO_AUTH_USER"
JVB_AUTH_USER = "CHANGEME-JVB_AUTH_USER"
JICOFO_AUTH_PASSWORD = "${password:32}"
JVB_AUTH_PASSWORD = "${password:32}"
JICOFO_COMPONENT_SECRET = "${password:32}"
JWT_APP_ID = "CHANGEME-JWT_APP_ID"
JWT_APP_SECRET = "${password:32}"
JVB_BREWERY_MUC = "CHANGEME-JVB_BREWERY_MUC"
JVB_PORT = "CHANGEME-JVB_PORT"
JVB_ADVERTISE_IPS = "CHANGEME-JVB_ADVERTISE_IPS"

[[routes]]
service = "web"
port = 8000
host = "${main_domain}"

[env]
PUBLIC_URL = "https://${main_domain}"
TZ = "UTC"
JITSI_IMAGE_VERSION = "${jitsi_image_version}"
XMPP_DOMAIN = "meet.jitsi"
XMPP_AUTH_DOMAIN = "auth.meet.jitsi"
XMPP_BOSH_URL_BASE = "http://prosody:5280"
XMPP_MUC_DOMAIN = "muc.meet.jitsi"
XMPP_INTERNAL_MUC_DOMAIN = "internal-muc.meet.jitsi"
XMPP_GUEST_DOMAIN = "guest.meet.jitsi"
XMPP_RECORDER_DOMAIN = "recorder.meet.jitsi"
ENABLE_AUTH = "0"
ENABLE_GUESTS = "1"
ENABLE_LETSENCRYPT = "0"
ENABLE_HTTP_REDIRECT = "0"
ENABLE_XMPP_WEBSOCKET = "1"
ENABLE_COLIBRI_WEBSOCKET = "1"
DISABLE_HTTPS = "1"
JICOFO_AUTH_USER = "focus"
JVB_AUTH_USER = "jvb"
JICOFO_AUTH_PASSWORD = "${jicofo_auth_password}"
JVB_AUTH_PASSWORD = "${jvb_auth_password}"
JICOFO_COMPONENT_SECRET = "${jicofo_component_secret}"
JVB_BREWERY_MUC = "jvbbrewery"
JVB_PORT = "10000"
JVB_ADVERTISE_IPS = ""
JWT_APP_ID = ""
JWT_APP_SECRET = ""
