[variables]
main_domain = "${domain}"
db_password = "${password:24}"
db_user = "danmuapi"
db_name = "danmuapi"
POSTGRES_PASSWORD = "${password:32}"
POSTGRES_USER = "CHANGEME-POSTGRES_USER"
POSTGRES_DB = "CHANGEME-POSTGRES_DB"
DANMUAPI_DATABASE__TYPE = "CHANGEME-DANMUAPI_DATABASE__TYPE"
DANMUAPI_DATABASE__PORT = "CHANGEME-DANMUAPI_DATABASE__PORT"
DANMUAPI_DATABASE__NAME = "CHANGEME-DANMUAPI_DATABASE__NAME"
DANMUAPI_DATABASE__USER = "CHANGEME-DANMUAPI_DATABASE__USER"
DANMUAPI_DATABASE__PASSWORD = "${password:32}"
DANMUAPI_ADMIN__INITIAL_USER = "CHANGEME-DANMUAPI_ADMIN__INITIAL_USER"

[[routes]]
service = "danmu-app"
port = 7768
host = "${main_domain}"

[env]
POSTGRES_PASSWORD = "${db_password}"
POSTGRES_USER = "${db_user}"
POSTGRES_DB = "${db_name}"
DANMUAPI_DATABASE__TYPE = "postgresql"
DANMUAPI_DATABASE__HOST = "postgres"
DANMUAPI_DATABASE__PORT = "5432"
DANMUAPI_DATABASE__NAME = "${db_name}"
DANMUAPI_DATABASE__USER = "${db_user}"
DANMUAPI_DATABASE__PASSWORD = "${db_password}"
DANMUAPI_ADMIN__INITIAL_USER = "admin"
