[variables]
gateway_token = "${password:32}"
auth_username = "dokploy"
auth_password = "${password:32}"
ANTHROPIC_API_KEY = "${password:32}"
OPENAI_API_KEY = "${password:32}"
GEMINI_API_KEY = "${password:32}"
XAI_API_KEY = "${password:32}"
GROQ_API_KEY = "${password:32}"
MISTRAL_API_KEY = "${password:32}"
CEREBRAS_API_KEY = "${password:32}"
VENICE_API_KEY = "${password:32}"
MOONSHOT_API_KEY = "${password:32}"
KIMI_API_KEY = "${password:32}"
MINIMAX_API_KEY = "${password:32}"
ZAI_API_KEY = "${password:32}"
AI_GATEWAY_API_KEY = "${password:32}"
OPENCODE_API_KEY = "${password:32}"
SYNTHETIC_API_KEY = "${password:32}"
COPILOT_GITHUB_TOKEN = "${password:32}"
XIAOMI_API_KEY = "${password:32}"
OPENCLAW_PRIMARY_MODEL = "CHANGEME-OPENCLAW_PRIMARY_MODEL"
DEEPGRAM_API_KEY = "${password:32}"
AWS_ACCESS_KEY_ID = "${password:32}"
AWS_SECRET_ACCESS_KEY = "${password:32}"
AWS_SESSION_TOKEN = "${password:32}"
openclaw_domain = "${domain}"

[[routes]]
service = "openclaw"
port = 8080
host = "${openclaw_domain}"

[env]
OPENCLAW_GATEWAY_TOKEN = "${gateway_token}"
OPENCLAW_GATEWAY_PORT = "18789"
AUTH_USERNAME = "${auth_username}"
AUTH_PASSWORD = "${auth_password}"
OPENCLAW_BRIDGE_PORT = "18790"
OPENCLAW_GATEWAY_BIND = "lan"
OPENCLAW_PLUGINS = "discord,memory-core"
OPENROUTER_API_KEY = "YOUR-API-KEY"
