services:
  ampache:
    image: ampache/ampache:nosql8.1.0
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - config:/var/www/config
      - log:/var/log/ampache
      - mysql:/var/lib/mysql
      - ${MEDIA_PATH}:/media
volumes:
  config: {}
  log: {}
  mysql: {}
