[variables]
main_domain = "${domain}"
registration_token = "${password:32}"

[[routes]]
service = "tuwunel"
port = 6167
host = "${main_domain}"

[env]
TUWUNEL_SERVER_NAME = "${main_domain}"
TUWUNEL_REGISTRATION_TOKEN = "${registration_token}"
