services:
  homebridge:
    image: homebridge/homebridge:2026-09-02
    restart: always
    expose:
      - 8581
    volumes:
      - homebridge-homebridge:/homebridge
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://homebridge:8581/
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
volumes:
  homebridge-homebridge: null
