[variables]
backend_domain = "${domain}"
frontend_domain = "${domain}"
AUTO_USERNAME_1 = "${username}"
AUTO_PASSWORD_2 = "${password}"
AUTO_USERNAME_3 = "${username}"
AUTO_PASSWORD_4 = "${password}"
AUTO_USERNAME_5 = "${username}"
AUTO_PASSWORD_6 = "${password}"

[[routes]]
service = "frontend"
port = 5173
host = "${frontend_domain}"

[[routes]]
service = "backend"
port = 1337
host = "${backend_domain}"

[env]
BACKEND_HOST = "${backend_domain}"
KANEO_DB = "kaneo"
KANEO_DB_USER = "${AUTO_USERNAME_5}"
KANEO_DB_PASSWORD = "${AUTO_PASSWORD_6}"
KANEO_JWT_ACCESS = "64"
