services:
  maxio:
    image: ghcr.io/coollabsio/maxio:0.2.1
    expose:
      - 9000
    volumes:
      - maxio-data:/data
    environment:
      - MAXIO_ACCESS_KEY=20
      - MAXIO_SECRET_KEY=20
    restart: unless-stopped
volumes:
  maxio-data: null
