services:
  doublezero:
    restart: always
    image: liltechnomancer/double-zero:0.2.1
    volumes:
      - db-data:/var/lib/doublezero/data
    environment:
      AWS_ACCESS_KEY_ID: your-aws-access-key
      AWS_SECRET_ACCESS_KEY: your-aws-secret-key
      AWS_REGION: your-aws-region
      SQS_URL: your-aws-sqs-url
      SYSTEM_EMAIL: ""
      SECRET_KEY_BASE: ${secret_key_base}
      PHX_HOST: ${main_domain}
      DATABASE_PATH: ./00.db
    expose:
      - 4000
volumes:
  db-data:
    driver: local
