services:
  flatnotes:
    image: dullage/flatnotes:v5.5.5
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      FLATNOTES_AUTH_TYPE: password
      FLATNOTES_USERNAME: ${AUTO_USERNAME_1}
      FLATNOTES_PASSWORD: ${AUTO_PASSWORD_2}
      FLATNOTES_SECRET_KEY: ${secret_key}
      FLATNOTES_SESSION_EXPIRY_DAYS: "30"
      FLATNOTES_TOTP_KEY: ""
      FLATNOTES_PATH_PREFIX: ""
      FLATNOTES_QUICK_ACCESS_HIDE: "false"
      FLATNOTES_QUICK_ACCESS_TITLE: RECENTLY MODIFIED
      FLATNOTES_QUICK_ACCESS_TERM: "*"
      FLATNOTES_QUICK_ACCESS_SORT: lastModified
      FLATNOTES_QUICK_ACCESS_LIMIT: "4"
    expose:
      - 8080
    volumes:
      - flatnotes-data:/data
volumes:
  flatnotes-data: {}
