[variables]
main_domain = "${domain}"
django_secret_key = "${password:8}"
database_password = "${password:16}"

[[routes]]
service = "flagsmith"
port = 8000
host = "${main_domain}"

[env]
DATABASE_PASSWORD = "${database_password}"
DJANGO_SECRET_KEY = "${django_secret_key}"
FLAGSMITH_DOMAIN = "${main_domain}"
