[variables]
main_domain = "${domain}"
db_password = "${password:16}"

[[routes]]
service = "chevereto"
port = 80
host = "${main_domain}"

[env]
DB_PASSWORD = "${db_password}"
DOMAIN = "${main_domain}"
