services:
  db:
    image: mariadb:10.11
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
      - MYSQL_DATABASE=limesurvey
      - MYSQL_USER=limesurvey
      - MYSQL_PASSWORD=${mysql_user_password}
  limesurvey:
    image: martialblog/limesurvey:7.0.15-260910-fpm-alpine
    restart: always
    volumes:
      - limesurvey_upload:/var/www/html/upload
    environment:
      - ADMIN_EMAIL=${admin_email}
      - ADMIN_NAME=Admin
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=${admin_password}
      - DB_HOST=db
      - DB_MYSQL_ENGINE=InnoDB
      - DB_NAME=limesurvey
      - DB_PASSWORD=${mysql_user_password}
      - DB_USERNAME=limesurvey
      - DEBUG=0
      - DEBUG_SQL=0
      - PUBLIC_URL=http://${main_domain}
      - SHOW_SCRIPT_NAME=false
      - URL_FORMAT=path
    depends_on:
      - db
    expose:
      - 8080
volumes:
  db_data: null
  limesurvey_upload: null
