services:
  ihatemoney:
    image: ihatemoney/ihatemoney:7.2.1
    environment:
      - DEBUG=False
      - ACTIVATE_DEMO_PROJECT=True
      - ACTIVATE_ADMIN_DASHBOARD=False
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ALLOW_PUBLIC_PROJECT_CREATION=True
      - BABEL_DEFAULT_TIMEZONE=UTC
      - GREENLET_TEST_CPP=no
      - MAIL_DEFAULT_SENDER=Budget manager <admin@example.com>
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PORT=25
      - MAIL_SERVER=localhost
      - MAIL_USE_SSL=False
      - MAIL_USE_TLS=False
      - MAIL_USERNAME=${MAIL_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - SESSION_COOKIE_SECURE=True
      - SHOW_ADMIN_EMAIL=True
      - SQLALCHEMY_DATABASE_URI=sqlite:////database/ihatemoney.db
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - APPLICATION_ROOT=/
      - ENABLE_CAPTCHA=False
      - LEGAL_LINK=
      - PORT=8000
      - PUID=0
      - PGID=0
    volumes:
      - ihatemoney-database:/database
    expose:
      - 8000
volumes:
  ihatemoney-database: null
