services:
  unleash:
    image: unleashorg/unleash-server:7.4.0
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${db_user}:${db_password}@db/${db_name}
      DATABASE_SSL: "false"
      LOG_LEVEL: warn
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit
        1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s
    volumes: []
    expose:
      - 4242
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - --username=${DB_USER}
        - --host=127.0.0.1
        - --port=5432
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
volumes:
  db_data: null
