[variables]
surrealdb_port = "8000"
open_notebook_port = "8502"
main_domain_surrealdb = "${domain}"
main_domain_open_notebook = "${domain}"
SURREAL_PASSWORD = "${password:32}"

[[routes]]
service = "surrealdb"
port = 8000
host = "surrealdb-${main_domain_surrealdb}"

[[routes]]
service = "open_notebook"
port = 8502
host = "${main_domain_open_notebook}"

[env]
SURREAL_URL = "ws://surrealdb:8000/rpc"
SURREAL_USER = "root"
SURREAL_PASSWORD = "${SURREAL_PASSWORD}"
SURREAL_NAMESPACE = "open_notebook"
SURREAL_DATABASE = "staging"
