services:
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:5
    restart: unless-stopped
    expose:
      - 8090
    volumes:
      - upsnap-data:/app/pb_data
    environment:
      - TZ=Europe/Berlin
      - UPSNAP_INTERVAL=*/10 * * * * *
      - UPSNAP_SCAN_RANGE=192.168.1.0/24
      - UPSNAP_SCAN_TIMEOUT=500ms
      - UPSNAP_PING_PRIVILEGED=true
      - UPSNAP_WEBSITE_TITLE=Upsnap Network Monitor
    healthcheck:
      test:
        - CMD
        - curl
        - -fs
        - http://localhost:8090/api/health
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  upsnap-data:
    driver: local
