[variables]
main_domain = "${domain}"
postgres_password = "${password:32}"

[[routes]]
service = "systemprompt"
port = 8080
host = "${main_domain}"

[env]
POSTGRES_PASSWORD = "${postgres_password}"
EXTERNAL_URL = "${main_domain}"
ANTHROPIC_API_KEY = "CHANGEME-replace-me"
OPENAI_API_KEY = "CHANGEME-replace-me"
GEMINI_API_KEY = "CHANGEME-replace-me"
