[variables]
main_domain = "${domain}"

[[routes]]
service = "grimoire"
port = 5173
host = "${main_domain}"

[env]
PORT = "5173"
PUBLIC_ORIGIN = "https://${main_domain}"
PUBLIC_HTTPS_ONLY = "true"
PUBLIC_SIGNUP_DISABLED = "false"
