services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.126.1
    volumes:
      - immich-library:/data
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-database:
        condition: service_healthy
    environment:
      DB_HOSTNAME: immich-database
      DB_PORT: "5432"
      DB_USERNAME: ${db_user}
      DB_PASSWORD: ${db_password}
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich-redis
      REDIS_PORT: "6379"
      REDIS_DBINDEX: "0"
      TZ: UTC
    restart: unless-stopped
    healthcheck:
      disable: false
    expose:
      - 2283
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.126.1
    volumes:
      - immich-model-cache:/cache
    restart: unless-stopped
    healthcheck:
      disable: false
  immich-redis:
    image: valkey/valkey:9
    volumes:
      - immich-redis-data:/data
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  immich-database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    volumes:
      - immich-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_USER: ${db_user}
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: --data-checksums
    shm_size: 128mb
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME} || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  immich-model-cache: null
  immich-postgres: null
  immich-library: null
  immich-redis-data: null
