[variables]
main_domain = "${domain}"
pg_pass = "${password}"

[[routes]]
service = "tooljet"
port = 80
host = "${main_domain}"

[env]
TOOLJET_HOST = "http://${main_domain}:80"
TOOLJET_HTTP_PROXY = "http://${main_domain}:80"
LOCKBOX_MASTER_KEY = "32"
SECRET_KEY_BASE = "64"
ORM_LOGGING = "all"
PG_DB = "tooljet_production"
PG_USER = "postgres"
PG_HOST = "postgres"
PG_PASS = "${pg_pass}"
TOOLJET_DB = "tooljet_db"
TOOLJET_DB_USER = "postgres"
TOOLJET_DB_HOST = "postgres"
TOOLJET_DB_PASS = "${pg_pass}"
PGRST_DB_URI = "postgres://postgres:${pg_pass}@postgres/tooljet_db"
PGRST_HOST = "localhost:3002"
PGRST_JWT_SECRET = "32"
PGRST_SERVER_PORT = "3002"
REDIS_HOST = "localhost"
REDIS_PORT = "6379"
REDIS_USER = "default"
REDIS_PASSWORD = ""
CHECK_FOR_UPDATES = "true"
DISABLE_TOOLJET_TELEMETRY = "true"
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
DEFAULT_FROM_EMAIL = "hello@tooljet.io"
SMTP_USERNAME = ""
SMTP_PASSWORD = ""
SMTP_DOMAIN = ""
SMTP_PORT = ""
DISABLE_SIGNUPS = ""
APM_VENDOR = ""
SENTRY_DNS = ""
SENTRY_DEBUG = ""
COMMENT_FEATURE_ENABLE = ""
ENABLE_MULTIPLAYER_EDITING = "true"
ENABLE_MARKETPLACE_FEATURE = "true"
SSO_GOOGLE_OAUTH2_CLIENT_ID = ""
SSO_GIT_OAUTH2_CLIENT_ID = ""
SSO_GIT_OAUTH2_CLIENT_SECRET = ""
SSO_GIT_OAUTH2_HOST = ""
SSO_ACCEPTED_DOMAINS = ""
SSO_DISABLE_SIGNUPS = ""
ENABLE_ONBOARDING_QUESTIONS_FOR_ALL_SIGN_UPS = ""
USER_SESSION_EXPIRY = "2880"
DEPLOYMENT_PLATFORM = "docker"
