services:
  tooljet:
    tty: true
    stdin_open: true
    image: tooljet/tooljet:ee-lts-latest
    restart: always
    expose:
      - 80
    depends_on:
      - postgres
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    command: npm run start:prod
    volumes: []
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - tooljet-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${pg_pass}
volumes:
  certs: null
  logs: null
  fallbackcerts: null
  tooljet-pgdata: null
